# cspell:words updatebot
# .github/release.yml
changelog:
  exclude:
    labels:
      - updatebot
  categories:
    - title: ✨ New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: 🔨 Other Changes
      labels:
        - "*"
