ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

=begin
  This function returns the min iOS version supported by React Native
  By using this function, you won't have to manually change your Podfile
  when we change the minimum version supported by the framework.
  min_ios_version_supported is defined in react_native_pods (current version is 12.4)
* ../node_modules/react-native/scripts/react_native_pods.rb#LL29-L31C4
=end
platform :ios, min_ios_version_supported
=begin
  This function prepares the project for React Native,
  before processing all the target exposed by the framework.
  Temporary solution to suppress duplicated GUID error.
  Can be removed once we move to generate files outside pod install.
* ../node_modules/react-native/scripts/react_native_pods.rb#LL35-L41C4
=end
prepare_react_native_project!
=begin
  If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
because `react-native-flipper` depends on (FlipperKit,...) that will be excluded from the build.
  To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
```javascript
  module.exports = {
dependencies: {
...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
```
=end
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'StepCounterExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # target 'StepCounterExampleTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
